# Generated by Django 5.2.13 on 2026-05-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_book_length_category_alter_book_genre_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('post_type', models.CharField(choices=[('list', 'Lista'), ('note', 'Nota')], db_index=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialPostBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_links', to='catalog.book')),
                ('editorial_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_books', to='editorial.editorialpost')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('editorial_post', 'book'), name='unique_editorial_post_book'), models.UniqueConstraint(fields=('editorial_post', 'position'), name='unique_editorial_post_position')],
            },
        ),
    ]
