# Generated by Django 5.2.13 on 2026-05-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialpost',
            name='post_type',
        ),
    ]
