# Generated by Django 5.2.13 on 2026-04-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('author_note_short', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('synopsis', models.TextField()),
                ('genre_main', models.CharField(choices=[('fantasy', 'Fantasía'), ('science_fiction', 'Ciencia ficción')], db_index=True, max_length=50)),
                ('page_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('available_in_spanish', models.BooleanField(db_index=True, default=True)),
                ('spanish_title', models.CharField(blank=True, max_length=255)),
                ('original_language', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('cover_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upgraded_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author')),
            ],
        ),
    ]
