# Generated by Django 5.2.13 on 2026-04-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre_main',
            field=models.CharField(choices=[('fantasy', 'Fantasia'), ('science_fiction', 'Ciencia ficcion')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('tone_primary', 'Tono principal'), ('tone_secondary', 'Tono secundario'), ('pace', 'Ritmo'), ('theme', 'Tematica')], db_index=True, max_length=50)),
                ('tag_value', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalog.book')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('book', 'tag_type', 'tag_value'), name='unique_book_tag_type_value')],
            },
        ),
    ]
