# Generated by Django 5.2.13 on 2026-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_genre_main_booktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='length_category',
            field=models.CharField(blank=True, choices=[('short', 'Corto'), ('medium', 'Medio'), ('long', 'Largo')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre_main',
            field=models.CharField(choices=[('fantasy', 'Fantasía'), ('science_fiction', 'Ciencia ficción')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='tag_type',
            field=models.CharField(choices=[('tone_primary', 'Tono principal'), ('tone_secondary', 'Tono secundario'), ('pace', 'Ritmo'), ('theme', 'Temática')], db_index=True, max_length=50),
        ),
    ]
