# Generated by Django 5.2.13 on 2026-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_length_category_alter_book_genre_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding_text',
            field=models.TextField(blank=True),
        ),
    ]
