# Generated by Django 5.2.13 on 2026-05-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_embedding_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='upgraded_at',
            new_name='updated_at',
        ),
    ]
