# Generated by Django 5.2.13 on 2026-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_upgraded_at_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='catalog_status',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('needs_review', 'Necesita revisión'), ('active', 'Activo'), ('inactive', 'Inactivo'), ('rejected', 'Rechazado')], db_index=True, default='candidate', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='external_google_books_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='external_openlibrary_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='external_wikidata_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='metadata_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('validated', 'Validada')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
