# Generated by Django 5.2.13 on 2026-04-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_book_length_category_alter_book_genre_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('query_text', models.TextField(blank=True)),
                ('tone_filter', models.CharField(blank=True, db_index=True, max_length=50)),
                ('pace_filter', models.CharField(blank=True, db_index=True, max_length=50)),
                ('theme_filter', models.CharField(blank=True, db_index=True, max_length=100)),
                ('length_filter', models.CharField(blank=True, db_index=True, max_length=20)),
                ('include_english', models.BooleanField(db_index=True, default=False)),
                ('user_agent_hash', models.CharField(blank=True, max_length=128)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.PositiveSmallIntegerField(db_index=True)),
                ('match_explanation', models.TextField()),
                ('shown_to_user', models.BooleanField(default=True)),
                ('clicked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='catalog.book')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracking.searchrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('search_request', 'rank_position'), name='unique_search_request_rank_position'), models.UniqueConstraint(fields=('search_request', 'book'), name='unique_search_request_book')],
            },
        ),
    ]
