# Generated by Django 5.2.13 on 2026-05-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('source', models.CharField(choices=[('search_results', 'Resultados de búsqueda'), ('newsletter_page', 'Página de newsletter'), ('editorial_page', 'Página editorial'), ('other', 'Otro')], db_index=True, max_length=50)),
                ('consent_newsletter', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateField(blank=True, null=True)),
                ('provider_contact_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
